export const initialState = {
  user: {
    userData: {
      id: null,
      name: null,
      email: null,
      phone_number: null,
      avatar_url: null,
      company_name: null,
      balance: null,
      tariff: {
        isActive: false,
        tariffName: "Demo",
        amountDue: null,
        camsNumber: null,
        dueDate: null,
      },
      session_id: null,
      role: null,
    },
    apiKey: null,
    isLoggedIn: false,
    isRefreshing: false,
    isLoading: false,
    error: null,
  },

  cars: {
    car: {
      id: null,
      status: null,
      photo: null,
      plate: null,
      checkInTime: null,
      makeModel: null,
      vin: null,
      engine: null,
      records: null,
      liftTime: null,
      year: null,
      mileage: null,
      brandPhoto: null,
      modelPhoto: null,
    },
    current: [],
    day: [],
    month: [],
    all: [],
    newCars: [],
    forHours: {},
    monthlyLoad: {},
    date: null,
    isLoading: false,
    error: null,
    loadPercent: null,
    queryMonth: null,
    workHours: {},
  },

  client: {
    name: null,
    phone: null,
    email: null,
    address: null,
    rating: null,
    date_of_birth: null,
    registration_date: null,
    last_visit: null,
    total_spent: 0,
    preferred_contact_method: null,
    notes: null,
    loyalty_program_status: null,
    number_of_visits: null,
    service_package: null,
    discount_type: null,
    emergency_service: null,
    next_service_date: null,
    source_of_contact: null,
    warranty_cases: null,
    special_offers: null,
    referral_count: null,
    discount_card_number: null,
    accumulated_bonus: null,
    related_customer_id: null,
    company_id: null,
  },
};
