// Статуси по машинах

export const statusesCar = [
  { status: "all", label: "Всі авто" },
  { status: "new", label: "Нові" },
  { status: "diagnostic", label: "Діагностика" },
  { status: "repair", label: "Ремонт" },
  { status: "view_repair", label: "Огляд ПР" },
  { status: "complete", label: "Завершено" },
];

// Статуси по клієнтах

export const statusesCommunications = [
  { status: "all_appeal", label: "Всі" },
  { status: "new_appeal", label: "Нові" },
  { status: "client", label: "Клієнти" },
  { status: "missing", label: "Втрачено" },
  { status: "appointment", label: "Запис" },
];

export const statusesArchive = [
  { reason_description: "all", label: "Всі авто" },
  { reason_description: "співробітник", label: "Cпівробітник" },
  { reason_description: "випадковий", label: "Випадковий" },
  { reason_description: "дубль", label: "Дубль" },
  { reason_description: "відмова", label: "Відмова" },
  { reason_description: "не_приїхав", label: "Не приїхав" },
  { reason_description: "рейтинг", label: "Рейтинг" },
  { reason_description: "не_допомогли", label: "Не допомогли" },
];

// Заголовки срм компоненті

export const statusMapping = {
  new: "Нова",
  diagnostic: "Діагностика",
  repair: "Ремонт",
  complete: "Завершено",
};

// пробний масив для компоненту зв'язку (клієнти)

  export const connections = [
    { timeCall: "9:39", typeMessage: "call_incoming", photoUrl: null, name: "Максим", auto: "HONDA CIVIC", status: "missing", callTranscription: null, content: null, clientId: null }, 
    { timeCall: "9:20", typeMessage: "call_missed", photoUrl: null, name: "Гість", auto: "HONDA CIVIC", status: "diagnostic", callTranscription: null, content: null, clientId: "123" },
    { timeCall: "9:27", typeMessage: "call_incoming", photoUrl: null, name: "Олександр Макаренковчук", auto: "2001 Volkswagen Passat", status: "repair", callTranscription: null, content: null, clientId: null },
    { timeCall: "9:15", typeMessage: "call_outgoing", photoUrl: null, name: "Петро", auto: "2001 HONDA CIVIC", status: "appointment", callTranscription: null, content: null, clientId: "456" },
    { timeCall: "9:39", typeMessage: "setting", photoUrl: null, name: "Максим", auto: "HONDA CIVIC", status: "diagnostic", callTranscription: null, content: null, clientId: null }, 
    { timeCall: "9:39", typeMessage: "browser", photoUrl: null, name: "Максим", auto: "HONDA CIVIC", status: "appointment", callTranscription: null, content: null, clientId: "789" }, 
    { timeCall: "9:27", typeMessage: "telegram", photoUrl: null, name: "Іван Петренко", auto: "2001 HONDA CIVIC", status: "repair", callTranscription: null, content: null, clientId: null },
    { timeCall: "9:27", typeMessage: "telegram", photoUrl: null, name: "Іван Петренко", auto: "2001 HONDA CIVIC", status: "repair", callTranscription: null, content: null, clientId: "987" },
    { timeCall: "9:27", typeMessage: "telegram", photoUrl: null, name: "Іван Петренко", auto: "2001 HONDA CIVIC", status: "repair", callTranscription: null, content: null, clientId: null },
    { timeCall: "9:27", typeMessage: "call_incoming", photoUrl: null, name: "Олександр Макаренковчук", auto: "2001 Volkswagen Passat", status: "repair", callTranscription: null, content: null, clientId: null },
    { timeCall: "9:27", typeMessage: "call_incoming", photoUrl: null, name: "Олександр Макаренковчук", auto: "2001 Volkswagen Passat", status: "repair", callTranscription: null, content: null, clientId: null }
  ];

// пробні статуси для компоненту зв'язку (клієнти)

export const statusesInConnections = {
  missing: "Втрачено",
  diagnostic: "Діагностика",
  repair: "Ремонт",
  appointment: "Запис",
};

// пробний масив для аудіоплеера

export const summary =
  "Привіт! Мене звати [Ім'я], і я хочу записатися на ремонт свого автомобіля. У мене[марка і модель авто], і після нещодавньої аварії потрібен огляд і ремонт кузова, зокрема вирівнювання геометрії та заміна пошкоджених деталей.Також цікавить діагностика стану автомобіля після ремонту.Чи є у вас вільні дати на цьому тижні, щоб я міг під'їхати на оцінку? Дякую!";

export const messages = [
  {
    orClientMsg: true,
    time: "00:00",
    message:
      "Доброго дня, ще раз заставлю. Скажіть, будь ласка, якщо я щось відвіду, я вам дзвоню, у мене нашовання блок АБС. Може хтось подивитися, це він чи не він?",
  },
  {
    orClientMsg: false,
    time: "00:15",
    message:
      "Можемо тільки з наступної середи, тому що електрик у нас відпустив.",
  },
  {
    orClientMsg: true,
    time: "00:00",
    message:
      "Доброго дня, ще раз заставлю. Скажіть, будь ласка, якщо я щось відвіду, я вам дзвоню, у мене нашовання блок АБС. Може хтось подивитися, це він чи не він?",
  },
  {
    orClientMsg: false,
    time: "00:15",
    message:
      "Можемо тільки з наступної середи, тому що електрик у нас відпустив.",
  },
  {
    orClientMsg: true,
    time: "00:00",
    message:
      "Доброго дня, ще раз заставлю. Скажіть, будь ласка, якщо я щось відвіду, я вам дзвоню, у мене нашовання блок АБС. Може хтось подивитися, це він чи не він?",
  },
  {
    orClientMsg: false,
    time: "00:15",
    message:
      "Можемо тільки з наступної середи, тому що електрик у нас відпустив.",
  },
];

// Лейбл для модлаки - налаштування видимості

export const labelNamesInModal = {
  name: "Ім'я",
  rating: "Рейтинг",
  carNum: "Номер машини",
  carModelYear: "Марка-модель",
  vin: "VIN",
  mileage: "Пробіг",
  time: "Час",
  photo: "Фото",
  totalPrice: "Загальна сума",
  phoneNumber: "Телефон",
  status: "Статус",
  info: "Інфо",
  prePayment: "Предоплата",
};

// Лейбл для архіву

export const labelNamesInArchive = {
  photo: "Фото",
  name: "Ім'я",
  carNum: "Номер машини",
  time: "Час",
  status: "Статус",
  reasonRegistration: "Причина запису",
  reasonArchived: "Причина архіву",
  btn: "Налаштування"
};

// Лейбл для CRM - налаштування видимості

export const labelNamesInCrm = {
  name: "Ім'я",
  rating: "Рейтинг",
  carNum: "Номер машини",
  carModelYear: "Марка-модель",
  vin: "VIN",
  mileage: "Пробіг",
  time: "Час",
  photo: "Фото",
  totalPrice: "Загальна сума",
  paymentBtn: "Оплатити",
  phoneNumber: "Телефон",
  status: "Статус",
  info: "Інфо",
  createBtn: "Створити запис",
  archive: "Архів",
  prePayment: "Предоплата",
};

// Лейбл для секції постачальників - налаштування видимості

export const labelNamesDistributorSection = {
  date: "Дата",
  quantity: "Кількість",
  article: "Артикул",
  brand: "Бренд",
  nomenclature: "Номенклатура",
  purchasePrice: "Ціна закупки",
  purchaseAmount: "Сума закупки",
  saleAmount: "Сума продажу",
  profit: "Прибуток",
  percent: "% прибутку",
};

// Лейбл для секції накладних - налаштування видимості

export const labelNamesInvoices = {
  diagnostics: "Діагностика",
  agreed: "Погоджено",
  reserved: "Замовлено",
  received: "Отримано",
  soldOut: "Продано",
  returned: "Повернуто",
  moved: "Переміщено",
  revaluation: "Переоцінка",
  inventory: "Інвентарізація",
  writeOff: "Списано",
};

// Прикожу назви в компонентів до назв в стані заголовки

export const categoryNameMapping = {
  Діагностика: "diagnostics",
  Погоджено: "agreed",
  Замовлено: "reserved",
  Отримано: "received",
  Продано: "soldOut",
  Повернуто: "returned",
  Переміщено: "moved",
  Переоцінка: "revaluation",
  Інвентаризація: "inventory",
  Списано: "writeOff",
};

// Лейбл для секції облік(клієнти у роботі) - налаштування видимості

export const labelNamesClientsInWork = {
  photo: "Фото",
  appeal: "Звернення",
  diagnostics: "Діагностика",
  KP: "КП",
  prePayment: "Аванс",
  order: "Замовлення",
  provider: "Постачальник",
  repair: "Ремонт",
  totalAmount: "Загальна сума",
  notification: "Сповіщення",
};

// export const categoryNameClients = {
//   "Звернення": "appeal",
//   "Діагностика": "diagnostics",
//   "КП": "KP",
//   "Замовлення": "order",
//   "Аванс": "prePayment",
//   "Постчальник": "provider",
//   "Ремонт": "repair",
//   "Тотальна сума": "totalAmount",
//   "Сповіщення": "notification"
// };

export const categoryIdClients = {
  0: "photo",
  1: "appeal",
  2: "diagnostics",
  3: "KP",
  4: "prePayment",
  5: "order",
  6: "provider",
  7: "repair",
  8: "totalAmount",
  9: "notification",
};

// Лейбл для секції облік(загальний список клієнтів) - налаштування видимості

export const labelNamesAllClients = {
  rating: "Рейтинг",
  appeal: "Звернення",
  repair: "Ремонт",
  averageCheck: "Середній чек",
  paydesk: "Каса",
  workPayment: "Оплата за роботу",
  salaryMechanics: "ЗП механіка",
  spareParts: "Запчастини",
  markUp: "Націнка",
  salaryManager: "ЗП Менеджер",
  salaryAdmin: "ЗП Адмін",
  coefficient: "Коефіцієнт",
  NG: "НГ",
  profit: "Прибуток",
  percent: "% прибутку",
};


    // Для PDF Постачальники дані

    export const dataArrDistributors = [
      {
        id: 1,
        orderDate: "02.02",
        distributorLogo: "",
        distributorName: "GRS PARTS",
        invoiceSum: "4610",
        delivered: true,
        deliveryDate: "03.02",
        carPartsQuantity: "7",
        profit: "1780",
        percent: "31",
        carImg: "",
        carNumber: "CA 6864 CO",
        salesAmount: "5800",
        carParts: [
          {
            quantity: 5,
            article: "214197",
            brandName: "MAZDA",
            carPartsName: "Олива MAZDA ORIGINAL",
            price: 600,
            salesAmount: 4300,
            purchaseAmount: "3000",
            salesPercent: "32",
          },
          {
            quantity: 1,
            article: "FZ0121500",
            brandName: "MAZDA",
            carPartsName: "Фильтр масляный АКПП",
            price: 1020,
            purchaseAmount: "1020",
            salesAmount: 1500,
            salesPercent: "33",
          },
          {
            quantity: 1,
            article: "KC 83D",
            brandName: "Knecht/Mah",
            carPartsName: "ФИЛЬТР ТОПЛИВА",
            price: 590,
            purchaseAmount: "590",
            salesAmount: "!",
            salesPercent: "-100%",
          },
          {
            quantity: 5,
            article: "214197",
            brandName: "MAZDA",
            carPartsName: "Олива MAZDA ORIGINAL",
            price: 600,
            purchaseAmount: "3000",
            salesAmount: 4300,
            salesPercent: "31",
          },
          {
            quantity: 1,
            article: "FZ0121500",
            brandName: "MAZDA",
            carPartsName: "Фильтр масляный АКПП",
            price: 1020,
            purchaseAmount: "1020",
            salesAmount: 1500,
            salesPercent: "10",
          },
          {
            quantity: 1,
            article: "KC 83D",
            brandName: "Knecht/Mah",
            carPartsName: "ФИЛЬТР ТОПЛИВА",
            price: 590,
            purchaseAmount: "590",
            salesAmount: "!",
            salesPercent: "-100%",
          },
        ],
      },
      {
        id: 2,
        orderDate: "02.02",
        distributorLogo: "",
        distributorName: "Elit.ua",
        invoiceSum: "5200",
        delivered: true,
        deliveryDate: "01.02",
        carPartsQuantity: "1",
        profit: "2200",
        percent: "37",
        carImg: "",
        carNumber: "CA 6864 CO",
        salesAmount: "6000",
        carParts: [
          {
            quantity: 1,
            article: "515483232",
            brandName: "MAZDA",
            carPartsName: "Важіль валу перемикання передач МКПП",
            price: "6000",
            purchaseAmount: "6000",
            salesAmount: "8300",
            salesPercent: "31",
          },
        ],
      },
      {
        id: 3,
        orderDate: "02.02",
        distributorLogo: "",
        distributorName: "GRS PARTS",
        invoiceSum: "4610",
        delivered: true,
        deliveryDate: "03.02",
        carPartsQuantity: "17",
        profit: "8000",
        percent: "31",
        carImg: "",
        carNumber: "CA 6864 CO",
        salesAmount: "5800",
        carParts: [
          {
            quantity: 5,
            article: "214197",
            brandName: "HYUNDAI",
            carPartsName: "Олива MAZDA ORIGINAL",
            price: 600,
            purchaseAmount: "3000",
            salesAmount: 4300,
            salesPercent: "31",
          },
          {
            quantity: 1,
            article: "FZ0121500",
            brandName: "HYUNDAI",
            carPartsName: "Фильтр масляный АКПП",
            price: 1020,
            purchaseAmount: "1020",
            salesAmount: 1500,
            salesPercent: "5",
          },
          {
            quantity: 1,
            article: "KC 83D",
            brandName: "HYUNDAI",
            carPartsName: "ФИЛЬТР ТОПЛИВА",
            price: 590,
            purchaseAmount: "590",
            salesAmount: null,
            salesPercent: null,
          },
          {
            quantity: 5,
            article: "214197",
            brandName: "MAZDA",
            carPartsName: "Олива MAZDA ORIGINAL",
            price: 600,
            purchaseAmount: "3000",
            salesAmount: 4300,
            salesPercent: "22",
          },
          {
            quantity: 1,
            article: "FZ0121500",
            brandName: "MAZDA",
            carPartsName: "Фильтр масляный АКПП",
            price: 1020,
            purchaseAmount: "1020",
            salesAmount: 1500,
            salesPercent: "25",
          },
          {
            quantity: 1,
            article: "KC 83D",
            brandName: "Knecht/Mah",
            carPartsName: "ФИЛЬТР ТОПЛИВА",
            price: 590,
            purchaseAmount: "590",
            salesAmount: null,
            salesPercent: null,
          },
        ],
      },
      {
        id: 4,
        orderDate: "03.02",
        distributorLogo: "",
        distributorName: "Elit.ua",
        invoiceSum: "5200",
        delivered: true,
        deliveryDate: "04.02",
        carPartsQuantity: "5",
        profit: "5000",
        percent: "37",
        carImg: "",
        carNumber: "CA 6864 CO",
        salesAmount: "6000",
        carParts: [
          {
            quantity: 1,
            article: "515483232",
            brandName: "MAZDA",
            carPartsName: "Важіль валу перемикання передач МКПП",
            price: "6000",
            purchaseAmount: "6000",
            salesAmount: "8300",
            salesPercent: "31",
          },
          {
            quantity: 1,
            article: "515483232",
            brandName: "MAZDA",
            carPartsName: "Важіль валу перемикання передач МКПП",
            price: "6000",
            purchaseAmount: "6000",
            salesAmount: "8300",
            salesPercent: "42",
          },
        ],
      },
      {
        id: 1,
        orderDate: "03.02",
        distributorLogo: "",
        distributorName: "GRS PARTS",
        invoiceSum: "4610",
        delivered: true,
        deliveryDate: "04.02",
        carPartsQuantity: "7",
        profit: "1780",
        percent: "31",
        carImg: "",
        carNumber: "CA 6864 CO",
        salesAmount: "5800",
        carParts: [
          {
            quantity: 5,
            article: "214197",
            brandName: "MAZDA",
            carPartsName: "Олива MAZDA ORIGINAL",
            price: 600,
            salesAmount: 4300,
            purchaseAmount: "3000",
            salesPercent: "32",
          },
          {
            quantity: 1,
            article: "FZ0121500",
            brandName: "MAZDA",
            carPartsName: "Фильтр масляный АКПП",
            price: 1020,
            purchaseAmount: "1020",
            salesAmount: 1500,
            salesPercent: "33",
          },
          {
            quantity: 1,
            article: "KC 83D",
            brandName: "Knecht/Mah",
            carPartsName: "ФИЛЬТР ТОПЛИВА",
            price: 590,
            purchaseAmount: "590",
            salesAmount: null,
            salesPercent: null,
          },
          {
            quantity: 5,
            article: "214197",
            brandName: "MAZDA",
            carPartsName: "Олива MAZDA ORIGINAL",
            price: 600,
            purchaseAmount: "3000",
            salesAmount: 4300,
            salesPercent: "31",
          },
          {
            quantity: 1,
            article: "FZ0121500",
            brandName: "MAZDA",
            carPartsName: "Фильтр масляный АКПП",
            price: 1020,
            purchaseAmount: "1020",
            salesAmount: 1500,
            salesPercent: "10",
          },
          {
            quantity: 1,
            article: "KC 83D",
            brandName: "Knecht/Mah",
            carPartsName: "ФИЛЬТР ТОПЛИВА",
            price: 590,
            purchaseAmount: "590",
            salesAmount: null,
            salesPercent: null,
          },
        ],
      },
      {
        id: 2,
        orderDate: "03.02",
        distributorLogo: "",
        distributorName: "Elit.ua",
        invoiceSum: "5200",
        delivered: true,
        deliveryDate: "05.02",
        carPartsQuantity: "1",
        profit: "2200",
        percent: "37",
        carImg: "",
        carNumber: "CA 6864 CO",
        salesAmount: "6000",
        carParts: [
          {
            quantity: 1,
            article: "515483232",
            brandName: "MAZDA",
            carPartsName: "Важіль валу перемикання передач МКПП",
            price: "6000",
            purchaseAmount: "6000",
            salesAmount: "8300",
            salesPercent: "31",
          },
        ],
      },
      {
        id: 3,
        orderDate: "03.02",
        distributorLogo: "",
        distributorName: "GRS PARTS",
        invoiceSum: "4610",
        delivered: true,
        deliveryDate: "05.02",
        carPartsQuantity: "17",
        profit: "8000",
        percent: "31",
        carImg: "",
        carNumber: "CA 6864 CO",
        salesAmount: "5800",
        carParts: [
          {
            quantity: 5,
            article: "214197",
            brandName: "HYUNDAI",
            carPartsName: "Олива MAZDA ORIGINAL",
            price: 600,
            purchaseAmount: "3000",
            salesAmount: 4300,
            salesPercent: "31",
          },
          {
            quantity: 1,
            article: "FZ0121500",
            brandName: "HYUNDAI",
            carPartsName: "Фильтр масляный АКПП",
            price: 1020,
            purchaseAmount: "1020",
            salesAmount: 1500,
            salesPercent: "5",
          },
          {
            quantity: 1,
            article: "KC 83D",
            brandName: "HYUNDAI",
            carPartsName: "ФИЛЬТР ТОПЛИВА",
            price: 590,
            purchaseAmount: "590",
            salesAmount: null,
            salesPercent: null,
          },
          {
            quantity: 5,
            article: "214197",
            brandName: "MAZDA",
            carPartsName: "Олива MAZDA ORIGINAL",
            price: 600,
            purchaseAmount: "3000",
            salesAmount: 4300,
            salesPercent: "22",
          },
          {
            quantity: 1,
            article: "FZ0121500",
            brandName: "MAZDA",
            carPartsName: "Фильтр масляный АКПП",
            price: 1020,
            purchaseAmount: "1020",
            salesAmount: 1500,
            salesPercent: "25",
          },
          {
            quantity: 1,
            article: "KC 83D",
            brandName: "Knecht/Mah",
            carPartsName: "ФИЛЬТР ТОПЛИВА",
            price: 590,
            purchaseAmount: "590",
            salesAmount: null,
            salesPercent: null,
          },
        ],
      },
      {
        id: 4,
        orderDate: "03.02",
        distributorLogo: "",
        distributorName: "Elit.ua",
        invoiceSum: "5200",
        delivered: true,
        deliveryDate: "04.02",
        carPartsQuantity: "5",
        profit: "5000",
        percent: "37",
        carImg: "",
        carNumber: "CA 6864 CO",
        salesAmount: "6000",
        carParts: [
          {
            quantity: 1,
            article: "515483232",
            brandName: "MAZDA",
            carPartsName: "Важіль валу перемикання передач МКПП",
            price: "6000",
            purchaseAmount: "6000",
            salesAmount: "8300",
            salesPercent: "31",
          },
          {
            quantity: 1,
            article: "515483232",
            brandName: "MAZDA",
            carPartsName: "Важіль валу перемикання передач МКПП",
            price: "6000",
            purchaseAmount: "6000",
            salesAmount: "8300",
            salesPercent: "42",
          },
        ],
      },
    ];

   export const dataGeneralClients = [
      {
        id: 6,
        parent: 0,
        date: "01.12",
        name: "Олександр Макаренковчук",
        raiting: 4,
        carcount: 4,
        connection: 7,
        repair: 4,
        middlecheck: 16000,
        cash: 64000,
        work: 30000,
        paymmechc: 12000,
        parts: 34000,
        mark: 34000,
        paymmng: 12000,
        paymadm: 12000,
        coeff: 1.7,
        ng: 700,
        income: 6613.83,
        percent: 23,
      },
      {
        id: 6,
        parent: 1,
        date: "01.12",
        name: "Іван Петренко",
        raiting: 4,
        carcount: 1,
        connection: 7,
        repair: 1,
        middlecheck: 16000,
        cash: 64000,
        work: 30000,
        paymmechc: 12000,
        parts: 34000,
        mark: 34000,
        paymmng: 12000,
        paymadm: 12000,
        coeff: 1.7,
        ng: 700,
        income: 6613.83,
        percent: 23,
      },
      {
        id: 6,
        parent: 1,
        date: "01.12",
        name: "Іван Петренко",
        raiting: 4,
        carcount: 1,
        connection: 7,
        repair: 1,
        middlecheck: 16000,
        cash: 64000,
        work: 30000,
        paymmechc: 12000,
        parts: 34000,
        mark: 34000,
        paymmng: 12000,
        paymadm: 12000,
        coeff: 1.7,
        ng: 700,
        income: 6613.83,
        percent: 23,
      },
      {
        id: 6,
        parent: 1,
        date: "01.12",
        name: "Іван Петренко",
        raiting: 4,
        carcount: 1,
        connection: 7,
        repair: 1,
        middlecheck: 16000,
        cash: 64000,
        work: 30000,
        paymmechc: 12000,
        parts: 34000,
        mark: 34000,
        paymmng: 12000,
        paymadm: 12000,
        coeff: 1.7,
        ng: 700,
        income: 6613.83,
        percent: 23,
      },
      {
        id: 6,
        parent: 1,
        date: "01.12",
        name: "Іван Петренко",
        raiting: 4,
        carcount: 1,
        connection: 7,
        repair: 1,
        middlecheck: 16000,
        cash: 64000,
        work: 30000,
        paymmechc: 12000,
        parts: 34000,
        mark: 34000,
        paymmng: 12000,
        paymadm: 12000,
        coeff: 1.7,
        ng: 700,
        income: 6613.83,
        percent: 23,
      },
      {
        id: 1,
        parent: 0,
        date: "04.12",
        name: "Іван Петренко",
        raiting: 3,
        carcount: 1,
        connection: 7,
        repair: 1,
        middlecheck: 12000,
        cash: 12000,
        work: 2000,
        paymmechc: 800,
        parts: 10000,
        mark: 4000,
        paymmng: 800,
        paymadm: 150,
        coeff: 1.7,
        ng: 700,
        income: 2100,
        percent: 12,
      },
    
      {
        id: 2,
        parent: 0,
        date: "04.12",
        name: "Іван Петренко",
        raiting: 3,
        carcount: 1,
        connection: 7,
        repair: 1,
        middlecheck: 12000,
        cash: 12000,
        work: 2000,
        paymmechc: 800,
        parts: 10000,
        mark: 4000,
        paymmng: 800,
        paymadm: 150,
        coeff: 1.7,
        ng: 700,
        income: 2100,
        percent: 12,
      },
    
      {
        id: 3,
        parent: 0,
        date: "04.12",
        name: "Іван Петренко",
        raiting: 3,
        carcount: 1,
        connection: 7,
        repair: 1,
        middlecheck: 12000,
        cash: 12000,
        work: 2000,
        paymmechc: 800,
        parts: 10000,
        mark: 4000,
        paymmng: 800,
        paymadm: 150,
        coeff: 1.7,
        ng: 700,
        income: 2100,
        percent: 12,
      },
      {
        id: 4,
        parent: 0,
        date: "04.12",
        name: "Іван Петренко",
        raiting: 3,
        carcount: 1,
        connection: 7,
        repair: 1,
        middlecheck: 12000,
        cash: 12000,
        work: 2000,
        paymmechc: 800,
        parts: 10000,
        mark: 4000,
        paymmng: 800,
        paymadm: 150,
        coeff: 1.7,
        ng: 700,
        income: 2100,
        percent: 12,
      },
    
      {
        id: 5,
        parent: 0,
        date: "03.12",
        name: "Іван Петренко",
        raiting: 4,
        carcount: 2,
        connection: 7,
        repair: 2,
        middlecheck: 10000,
        cash: 34000,
        work: 10000,
        paymmechc: 2000,
        parts: 3000,
        mark: 3000,
        paymmng: 2000,
        paymadm: 100,
        coeff: 1.7,
        ng: 700,
        income: 4613.83,
        percent: 18,
      },
      {
        id: 5,
        parent: 1,
        date: "01.12",
        name: "Іван Петренко",
        raiting: 4,
        carcount: 1,
        connection: 7,
        repair: 1,
        middlecheck: 10000,
        cash: 34000,
        work: 10000,
        paymmechc: 2000,
        parts: 3000,
        mark: 3000,
        paymmng: 2000,
        paymadm: 100,
        coeff: 1.7,
        ng: 700,
        income: 4613.83,
        percent: 18,
      },
      {
        id: 5,
        parent: 1,
        date: "01.12",
        name: "Іван Петренко",
        raiting: 2,
        carcount: 1,
        connection: 7,
        repair: 1,
        middlecheck: 10000,
        cash: 34000,
        work: 10000,
        paymmechc: 2000,
        parts: 3000,
        mark: 3000,
        paymmng: 2000,
        paymadm: 100,
        coeff: 1.7,
        ng: 700,
        income: 4613.83,
        percent: 18,
      },
    ];

    